apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homer-operator-clusterrole
rules:
- apiGroups: ["homer-operator.j3nko.de"]
  resources: ["homerservices", "homerconfig"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homer-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
- kind: Group
  name: system:serviceaccount:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: homer-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
