apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: homerservices.homer-operator.j3nko.de
spec:
  scope: Namespaced
  group: homer-operator.j3nko.de
  names:
    kind: HomerService
    plural: homerservices
    singular: homerservice
    shortNames:
      - hs
      - hss
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: homerconfig.homer-operator.j3nko.de
spec:
  scope: Namespaced
  group: homer-operator.j3nko.de
  names:
    kind: HomerConfig
    plural: homerconfig
    singular: homerconfig
    shortNames:
      - hc
      - hcs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
